# Generated by Django 5.2.8 on 2025-11-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='expiriens',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_grade', models.IntegerField(blank=True, null=True)),
                ('letter_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('rel_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student')),
                ('rel_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_variant', models.CharField(choices=[('MON', 'понеділок'), ('TUE', 'вівторок'), ('WED', 'середа'), ('THU', 'четвер'), ('FRI', "п'ятниця")], max_length=3)),
                ('lesson_number', models.IntegerField()),
                ('conn_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.class')),
                ('conn_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subject')),
                ('conn_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher')),
            ],
            options={
                'unique_together': {('day_variant', 'lesson_number', 'conn_class')},
            },
        ),
    ]
