# Generated by Django 5.2.8 on 2025-11-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_rename_expiriens_teacher_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(max_length=30),
        ),
    ]
